# Generated by Django 3.2.6 on 2021-08-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayset',
            name='date',
            field=models.DateField(auto_now=True, unique=True),
        ),
    ]
